# Generated by Django 5.2.8 on 2025-11-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='level',
            field=models.CharField(choices=[('SHS', 'Senior High School'), ('Bachelor', 'Bachelor'), ('Masteral', 'Masteral')], default='Bachelor', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('name', 'level')},
        ),
    ]
