# Generated by Django 5.2.8 on 2025-11-11 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_subject_archived"),
        ("enrollment", "0003_term_level_alter_term_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("term", "section_code")},
        ),
        migrations.AddField(
            model_name="section",
            name="professors",
            field=models.ManyToManyField(
                limit_choices_to={"role": "professor"},
                related_name="sections_taught",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="subjects",
            field=models.ManyToManyField(
                related_name="sections", to="academics.subject"
            ),
        ),
        migrations.RemoveField(
            model_name="section",
            name="professor",
        ),
        migrations.RemoveField(
            model_name="section",
            name="subject",
        ),
    ]
