# Generated by Django 5.2.8 on 2025-11-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "enrollment",
            "0004_alter_section_unique_together_section_professors_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="term",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
