# Generated by Django 5.2.8 on 2025-11-12 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_subject_archived"),
        ("enrollment", "0005_term_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="onboarding_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="student",
            name="curriculum",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.curriculum",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.program",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("graduated", "Graduated"),
                ],
                default="inactive",
                max_length=20,
            ),
        ),
    ]
