# Generated by Django 5.2.8 on 2025-11-13 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject_archived'),
        ('enrollment', '0009_student_student_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransfereeEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('transfer_type', models.CharField(choices=[('same_school', 'Transfer within same school (different course)'), ('external_school', 'Transfer from another school')], max_length=20)),
                ('source_school', models.CharField(help_text='Name of school transferring from', max_length=255)),
                ('source_program', models.CharField(help_text='Program name at source school', max_length=255)),
                ('status', models.CharField(choices=[('pending_credential_input', 'Pending - Credential Input'), ('pending_tor_verification', 'Pending - TOR Verification'), ('tor_verified', 'TOR Verified - Ready for Account Creation'), ('account_created', 'Account Created - Transferee Account Active'), ('rejected', 'Rejected')], default='pending_credential_input', max_length=30)),
                ('tor_verified', models.BooleanField(default=False)),
                ('tor_verified_at', models.DateTimeField(blank=True, null=True)),
                ('account_created_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from registrar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_created_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['registrar', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transferee_accounts', to=settings.AUTH_USER_MODEL)),
                ('created_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferee_enrollment', to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.curriculum')),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.program')),
                ('tor_verified_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['registrar', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_transferees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransfereeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_subject_code', models.CharField(help_text='Subject code from source school', max_length=50)),
                ('source_subject_name', models.CharField(help_text='Subject name from source school', max_length=255)),
                ('grade', models.CharField(help_text='Grade from TOR (e.g., 2.5, A, B+, etc.)', max_length=5)),
                ('status', models.CharField(choices=[('credited', 'Credited'), ('rejected', 'Rejected')], default='credited', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('credited_at', models.DateTimeField(auto_now_add=True)),
                ('credited_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['registrar', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credited_subjects', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, help_text='Subject at Richwell College', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject')),
                ('transferee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='enrollment.transfereeenrollment')),
            ],
        ),
    ]
