# Generated by Django 5.2.8 on 2025-11-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
